@echo off
echo Limpiando...
call C:\src\flutter\bin\flutter clean
echo Obteniendo paquetes...
call C:\src\flutter\bin\flutter pub get
echo Lanzando App (Intento 2)...
call C:\src\flutter\bin\flutter run -d chrome --web-browser-flag "--disable-web-security"
pause
